# Attention: if you submit an improvement for a Namecoin Cirrus config, please
# file a GitHub issue about it at the namecoin/meta repo, so that we can make
# sure it propagates to all the other Namecoin repos.  Thanks!

task:
  alias: Go Lint
  container:
    image: golangci/golangci-lint:latest
  fetch_script:
    - go mod init github.com/"$CIRRUS_REPO_FULL_NAME"
    - go mod tidy
  # Disable maligned because it's deprecated by author in favoooooor of govet fieldalignment.
  # Disable tagliatelle because it interferes with JSON protocol used by Namecoin Core.
  lint_script: golangci-lint run --enable-all --disable exhaustivestruct,exhaustruct,gochecknoglobals,gochecknoinits,gomnd,maligned,tagliatelle $GOLANGCI_ARGS -v --out-format json > lint-report.json
  matrix:
    - name: Go Lint $GOOS New
      env:
        GOLANGCI_ARGS: "--new-from-rev=HEAD~"
    - name: Go Lint $GOOS Mandatory
      env:
        GOLANGCI_ARGS: ""
    - name: Go Lint $GOOS
      env:
        GOLANGCI_ARGS: ""
      allow_failures: true
  matrix:
    - env:
        GOOS: linux
    - env:
        GOOS: windows
  always:
    golangci_artifacts:
      path: lint-report.json
      type: text/json
      format: golangci

task:
  name: Cross-Compile Go $GO_VERSION
  alias: Cross-Compile
  container:
    image: golang:$GO_VERSION
    cpu: 8
    memory: 8G
  install_script:
    - go install github.com/mitchellh/gox@latest
  fetch_script:
    - go mod init github.com/"$CIRRUS_REPO_FULL_NAME"
    - go mod tidy
  build_script:
    - rm -rf idist
    # Nothing in this repo needs cgo.
    - CGO_ENABLED=0 gox -tags="$GOX_TAGS" -parallel=8 -osarch 'darwin/amd64 linux/386 linux/amd64 linux/arm linux/arm64 linux/ppc64 linux/ppc64le freebsd/386 freebsd/amd64 freebsd/arm openbsd/386 openbsd/amd64 netbsd/386 netbsd/amd64 netbsd/arm dragonfly/amd64 solaris/amd64 windows/386 windows/amd64' -output "$GOPATH/releasing/idist/$CIRRUS_REPO_NAME-$CIRRUS_TAG-{{.OS}}_{{.Arch}}/bin/{{.Dir}}" github.com/$CIRRUS_REPO_FULL_NAME/...
    - mv $GOPATH/releasing/idist ./idist
  env:
    GOX_TAGS: ""
    GO_VERSION: latest

# TODO: Add Windows unit tests

# TODO: "Testing config parsing" from travis.bash

# TODO: Add multiple Go versions to Gox builds and unit tests

# TODO: Add debug stripping and path stripping to Gox for repro builds

# TODO: Re-add darwin/386 for old Go versions where it was supported

# TODO: Fix upload repo for tagged commits (don't use Nightly repo for this)

# TODO: Skip Signify and Release if it's not applicable

# TODO: Signify Nightlies

# TODO: IRC notifications on failure

# TODO: Cron
